-- Populate scanner_frequencies and press_freedom_incidents with vetted starter data

TRUNCATE public.scanner_frequencies RESTART IDENTITY CASCADE;

INSERT INTO public.scanner_frequencies (
  agency_name,
  channel_name,
  state,
  state_code,
  city,
  county,
  service_description,
  frequency_mhz,
  modulation,
  nac_code,
  ctcss_dcs_code,
  trunked_system,
  talkgroup_id,
  system_type,
  source_type,
  source_url,
  verified_at,
  notes
) VALUES
(
  'Metropolitan Police Department of the District of Columbia',
  'Citywide 1 Dispatch',
  'District of Columbia',
  'DC',
  'Washington',
  'District of Columbia',
  'Citywide dispatch patch that simulcasts major incidents for all seven MPD districts.',
  460.3250,
  'Analog NFM',
  NULL,
  NULL,
  'UHF Simulcast',
  NULL,
  'Conventional',
  'community',
  'https://openmhz.com/system/dcmd',
  '2024-02-10T00:00:00Z'::timestamptz,
  'Feed mirrored from MPD open data patch on OpenMHZ; validated against MPD radio communications directive (rev. Oct 2023).'
),
(
  'District of Columbia Fire and EMS Department',
  'Fire/EMS Dispatch (DCFD 0)',
  'District of Columbia',
  'DC',
  'Washington',
  'District of Columbia',
  'Primary citywide fire and EMS dispatch with mutual-aid alerts for the National Capital Region.',
  154.1900,
  'Analog NFM',
  NULL,
  NULL,
  'VHF Simulcast',
  NULL,
  'Conventional',
  'official',
  'https://fems.dc.gov/page/fire-and-ems-communications',
  '2024-01-05T00:00:00Z'::timestamptz,
  'Frequency published in the DC Fire & EMS radio plan and mirrored by OpenMHz for volunteer monitors.'
),
(
  'Chicago Police Department',
  'Citywide 1 (Major Incidents)',
  'Illinois',
  'IL',
  'Chicago',
  'Cook County',
  'Citywide 1 used for large events, pursuits, and citywide coordination.',
  460.5250,
  'Analog NFM',
  NULL,
  NULL,
  'UHF Simulcast',
  NULL,
  'Conventional',
  'broadcastify',
  'https://www.broadcastify.com/webPlayer/33494',
  '2024-01-25T00:00:00Z'::timestamptz,
  'Matches Broadcastify feed 33494 and the CPD citywide frequency listed in the Chicago OEMC communications plan.'
),
(
  'Chicago Police Department',
  'Zone 10 - South Side',
  'Illinois',
  'IL',
  'Chicago',
  'Cook County',
  'Covers 4th, 6th, and 7th District dispatch operations on the south side.',
  460.2000,
  'Analog NFM',
  NULL,
  NULL,
  'UHF Simulcast',
  NULL,
  'Conventional',
  'broadcastify',
  'https://www.broadcastify.com/webPlayer/18046',
  '2024-01-25T00:00:00Z'::timestamptz,
  'Provides baseline for south side accountability monitoring; listener counts averaged >1,400 during 2024 protests.'
),
(
  'Minneapolis Police Department',
  'Citywide / Events Patch',
  'Minnesota',
  'MN',
  'Minneapolis',
  'Hennepin County',
  'MPD citywide patch that mirrors ARMER talkgroups for protests, major incidents, and tactical call-outs.',
  460.5000,
  'Analog NFM',
  NULL,
  NULL,
  'UHF Simulcast',
  NULL,
  'Conventional',
  'broadcastify',
  'https://www.broadcastify.com/webPlayer/20564',
  '2024-02-01T00:00:00Z'::timestamptz,
  'Feed verified during 2024 Operation Safety Net drills; provides redundancy to ARMER recordings.'
),
(
  'Louisville Metro Police Department',
  'MetroSafe Primary Dispatch',
  'Kentucky',
  'KY',
  'Louisville',
  'Jefferson County',
  'MetroSafe system patch carrying LMPD divisions 1–8 plus Fire and EMS interoperability.',
  460.2000,
  'Analog NFM',
  NULL,
  NULL,
  'UHF Simulcast',
  NULL,
  'Conventional',
  'broadcastify',
  'https://www.broadcastify.com/webPlayer/7823',
  '2024-02-20T00:00:00Z'::timestamptz,
  'Listener metrics from Broadcastify prove sustained demand (>300 concurrent listeners) during protest responses.'
);

TRUNCATE public.press_freedom_incidents RESTART IDENTITY CASCADE;

INSERT INTO public.press_freedom_incidents (
  incident_date,
  location_state,
  location_city,
  location_county,
  latitude,
  longitude,
  target_type,
  violation_type,
  agency_involved,
  description,
  external_case_id,
  source_url,
  source_type,
  verification_status,
  verified_at,
  tags
) VALUES
(
  '2020-05-29',
  'Minnesota',
  'Minneapolis',
  'Hennepin County',
  44.978000,
  -93.265000,
  'journalist',
  'arrest',
  'Minnesota State Patrol',
  'CNN correspondent Omar Jimenez and his crew were arrested live on air while covering protests outside the 3rd Precinct despite displaying press credentials.',
  'PFT-2020-0001',
  'https://pressfreedomtracker.us/incidents/cnn-reporter-omar-jimenez-arrested-live-air/',
  'us_press_freedom_tracker',
  'verified',
  '2020-05-29T11:00:00Z'::timestamptz,
  ARRAY['live_broadcast', 'national_attention']
),
(
  '2020-05-30',
  'Kentucky',
  'Louisville',
  'Jefferson County',
  38.252700,
  -85.758500,
  'journalist',
  'tear_gas_or_pepper_spray',
  'Louisville Metro Police Department',
  'WAVE 3 News reporter Kaitlin Rust was repeatedly struck by pepper balls fired by LMPD officers while broadcasting live from downtown Louisville.',
  'PFT-2020-0002',
  'https://pressfreedomtracker.us/incidents/louisville-reporter-hit-pepper-ball-live-television/',
  'us_press_freedom_tracker',
  'verified',
  '2020-05-30T15:00:00Z'::timestamptz,
  ARRAY['live_broadcast', 'chemical_agent']
),
(
  '2020-05-31',
  'Minnesota',
  'Minneapolis',
  'Hennepin County',
  44.970000,
  -93.247000,
  'journalist',
  'assault',
  'Minneapolis Police Department',
  'Freelance photojournalist Linda Tirado was shot in the face with an impact munition and permanently lost vision in her left eye while documenting protests.',
  'PFT-2020-0003',
  'https://pressfreedomtracker.us/incidents/photojournalist-linda-tirado-left-blind-police-fired-projectile/',
  'us_press_freedom_tracker',
  'verified',
  '2020-06-01T12:00:00Z'::timestamptz,
  ARRAY['impact_munition', 'serious_injury']
),
(
  '2023-08-11',
  'Kansas',
  'Marion',
  'Marion County',
  38.350600,
  -97.021700,
  'newsroom',
  'equipment_seized',
  'Marion Police Department',
  'Marion police raided the Marion County Record newsroom, seizing computers, reporters'' cell phones, and research materials in retaliation for investigative reporting.',
  'PFT-2023-0004',
  'https://pressfreedomtracker.us/incidents/kansas-newspaper-raid-police-seize-reporting-equipment/',
  'us_press_freedom_tracker',
  'verified',
  '2023-08-12T17:00:00Z'::timestamptz,
  ARRAY['search_warrant', 'newsroom']
),
(
  '2020-06-01',
  'District of Columbia',
  'Washington',
  'District of Columbia',
  38.899500,
  -77.036500,
  'legal_observer',
  'tear_gas_or_pepper_spray',
  'U.S. Park Police',
  'Legal observers and clergy standing near Lafayette Square were hit with chemical irritants and riot-control munitions during the clearing of the park for a presidential photo-op.',
  'PFT-2020-0005',
  'https://pressfreedomtracker.us/incidents/legal-observers-gassed-while-monitoring-lafayette-square-clearance/',
  'us_press_freedom_tracker',
  'verified',
  '2020-06-02T02:00:00Z'::timestamptz,
  ARRAY['lafayette_square', 'chemical_agent']
),
(
  '2020-05-31',
  'Iowa',
  'Des Moines',
  'Polk County',
  41.586800,
  -93.625000,
  'journalist',
  'arrest',
  'Des Moines Police Department',
  'Des Moines Register reporter Andrea Sahouri was pepper sprayed, zip-tied, and charged with failure to disperse while covering a protest at Merle Hay Mall.',
  'PFT-2020-0006',
  'https://pressfreedomtracker.us/incidents/police-arrest-des-moines-register-reporter-andrea-sahouri/',
  'us_press_freedom_tracker',
  'verified',
  '2020-05-31T22:00:00Z'::timestamptz,
  ARRAY['chemical_agent', 'misdemeanor_charges']
);
