-- Seed curated resources to support activists, legal observers, and community members

INSERT INTO public.resource_library (
  title,
  description,
  resource_type,
  category,
  file_url,
  file_size,
  external_url,
  author,
  source,
  language,
  tags,
  is_approved
) VALUES
('Know Your Rights During Protests (2024 Update)',
  'Step-by-step protest guide covering detentions, searches, and filming police in all 50 states.',
  'pdf',
  'Legal Guides',
  NULL,
  NULL,
  'https://www.nlg.org/wp-content/uploads/2024/03/NLG-Know-Your-Rights-Guide.pdf',
  'National Lawyers Guild',
  'National Lawyers Guild',
  'en',
  ARRAY['protest', 'know-your-rights', 'police'],
  true),
('Digital Security for Protesters',
  'Checklist for securing phones, managing live streams, and protecting evidence before demonstrations.',
  'link',
  'Digital Safety',
  NULL,
  NULL,
  'https://ssd.eff.org/module/digital-security-protesters',
  'Electronic Frontier Foundation',
  'EFF Security Education Companion',
  'en',
  ARRAY['digital-security', 'livestream', 'evidence'],
  true),
('Rapid Response Bail Fund Directory',
  'National directory of community bail funds and verified mutual aid groups that respond to protest arrests.',
  'link',
  'Support Networks',
  NULL,
  NULL,
  'https://www.communityjusticeexchange.org/nbfn-directory',
  'Community Justice Exchange',
  'Community Justice Exchange',
  'en',
  ARRAY['bail-support', 'mutual-aid', 'organizing'],
  true),
('Template: Civilian Complaint Letter for Police Misconduct',
  'Editable template for documenting police misconduct and filing complaints with oversight boards.',
  'document',
  'Forms & Templates',
  NULL,
  NULL,
  'https://civilrightshub.org/resources/templates/police-misconduct-complaint.docx',
  'Civil Rights Hub',
  'Civil Rights Hub',
  'en',
  ARRAY['template', 'police-misconduct', 'accountability'],
  true),
('Emergency Legal Hotline Wallet Card',
  'Printable wallet card with Miranda reminders, hotline numbers, and quick reference rights.',
  'pdf',
  'Legal Guides',
  NULL,
  NULL,
  'https://civilrightshub.org/resources/cards/emergency-legal-hotline-card.pdf',
  'Civil Rights Hub',
  'Civil Rights Hub',
  'en',
  ARRAY['miranda', 'hotline', 'printable'],
  true),
('Mental Health Toolkit for Organizers',
  'Grounding exercises, support hotlines, and therapist directories tailored to movement organizers.',
  'pdf',
  'Wellness & Healing',
  NULL,
  NULL,
  'https://docs.google.com/document/d/mental-health-toolkit-activists',
  'Therapy for Black Lives',
  'Therapy for Black Lives',
  'en',
  ARRAY['mental-health', 'healing-justice', 'organizers'],
  true),
('Language Access Guide for Legal Observers',
  'Rapid translation phrases and best practices for multilingual protest response teams.',
  'pdf',
  'Legal Guides',
  NULL,
  NULL,
  'https://civilrightshub.org/resources/guides/language-access-legal-observers.pdf',
  'Civil Rights Hub',
  'Civil Rights Hub',
  'en',
  ARRAY['language-access', 'legal-observer', 'interpretation'],
  true),
('Video: How to Document Police Conduct Safely',
  'Training covering filming techniques, evidence preservation, and uploading securely from the field.',
  'video',
  'Training & Workshops',
  NULL,
  NULL,
  'https://vimeo.com/rights-training/police-documentation',
  'WITNESS',
  'WITNESS',
  'en',
  ARRAY['video', 'documentation', 'police'],
  true),
('FOIA Toolkit for Accountability Journalism',
  'Comprehensive toolkit for filing FOIA, state sunshine requests, and appeals related to policing.',
  'pdf',
  'Public Records',
  NULL,
  NULL,
  'https://www.rcfp.org/resources/foia-toolkit-2024.pdf',
  'Reporters Committee for Freedom of the Press',
  'RCFP',
  'en',
  ARRAY['foia', 'public-records', 'journalism'],
  true),
('De-Escalation and Street Safety Training Slides',
  'Slides used to train marshals and community safety teams on de-escalation techniques.',
  'pdf',
  'Training & Workshops',
  NULL,
  NULL,
  'https://civilrightshub.org/resources/slides/de-escalation-training.pdf',
  'Safe Protest Collective',
  'Safe Protest Collective',
  'en',
  ARRAY['de-escalation', 'training', 'marshals'],
  true),
('Mutual Aid Coordination Playbook',
  'Playbook for organizing supply drops, court support, and jail release logistics during actions.',
  'document',
  'Support Networks',
  NULL,
  NULL,
  'https://mutualaidhub.org/resources/mutual-aid-playbook.docx',
  'Mutual Aid Hub',
  'Mutual Aid Hub',
  'en',
  ARRAY['mutual-aid', 'logistics', 'support'],
  true),
('Know Your Rights for Immigrant Protesters',
  'Explains additional considerations for undocumented and mixed-status protesters, including ICE interactions.',
  'pdf',
  'Legal Guides',
  NULL,
  NULL,
  'https://www.nilc.org/wp-content/uploads/2024/02/Immigrant-Protester-KYR.pdf',
  'National Immigration Law Center',
  'NILC',
  'en',
  ARRAY['immigration', 'know-your-rights', 'protest'],
  true),
('Audio: Trauma-Informed Support After Arrest',
  'Guided audio session helping activists process trauma following arrests or police violence.',
  'audio',
  'Wellness & Healing',
  NULL,
  NULL,
  'https://civilrightshub.org/resources/audio/trauma-informed-support.mp3',
  'Healing Justice Coalition',
  'Healing Justice Coalition',
  'en',
  ARRAY['trauma', 'healing', 'audio'],
  true),
('Guide: Filing Federal Civil Rights Lawsuits',
  'Overview of Section 1983 litigation, deadlines, evidence preservation, and connecting with legal teams.',
  'pdf',
  'Legal Guides',
  NULL,
  NULL,
  'https://civilrightshub.org/resources/guides/filing-section-1983-claims.pdf',
  'Civil Rights Hub',
  'Civil Rights Hub',
  'en',
  ARRAY['section-1983', 'litigation', 'evidence'],
  true);
