-- Seed data for court_calendars table - Civil rights hearings and trials

INSERT INTO public.court_calendars (
  case_name,
  case_number,
  case_type,
  description,
  court_name,
  court_type,
  city,
  state,
  address,
  hearing_date,
  hearing_type,
  judge_name,
  plaintiff,
  defendant,
  is_public,
  zoom_link,
  phone_number,
  courtroom,
  organizations_involved,
  issues,
  external_url,
  notes,
  status
) VALUES

-- Scheduled hearings
(
  'Johnson v. City Police Department',
  '2024-CV-8832',
  'Police Misconduct',
  'Section 1983 civil rights lawsuit alleging excessive force during traffic stop. Plaintiff seeks damages for injuries sustained and violation of Fourth Amendment rights.',
  'U.S. District Court for the Northern District of California',
  'Federal District',
  'San Francisco',
  'California',
  '450 Golden Gate Ave, San Francisco, CA 94102',
  '2025-11-20 09:00:00-08',
  'Motion Hearing',
  'Hon. Maria Rodriguez',
  'Marcus Johnson',
  'City of San Francisco Police Department',
  true,
  'https://ndcal.zoomgov.com/j/1234567890',
  '888-363-4749',
  'Courtroom 11',
  ARRAY['ACLU of Northern California', 'National Police Accountability Project'],
  ARRAY['Fourth Amendment', 'Excessive Force', 'Qualified Immunity'],
  NULL,
  'Motion to dismiss based on qualified immunity defense',
  'scheduled'
),

(
  'NAACP v. State Board of Elections',
  '2024-CV-1156',
  'Voting Rights',
  'Voting Rights Act Section 2 challenge to redistricting plan alleging racial gerrymandering and vote dilution in minority communities.',
  'U.S. District Court for the Northern District of Georgia',
  'Federal District',
  'Atlanta',
  'Georgia',
  '75 Ted Turner Dr SW, Atlanta, GA 30303',
  '2025-11-18 14:00:00-05',
  'Preliminary Injunction Hearing',
  'Hon. David Chen',
  'NAACP Georgia Chapter',
  'Georgia State Board of Elections',
  true,
  'https://gand.zoomgov.com/j/9876543210',
  '877-336-1839',
  'Courtroom 2304',
  ARRAY['NAACP Legal Defense Fund', 'Southern Poverty Law Center', 'Lawyers Committee for Civil Rights'],
  ARRAY['Voting Rights Act', 'Racial Gerrymandering', 'Vote Dilution'],
  'https://www.naacpldf.org/',
  'Seeking preliminary injunction to block new district maps before next election',
  'scheduled'
),

(
  'Martinez v. Immigration and Customs Enforcement',
  '2024-CV-4523',
  'Civil Rights',
  'Class action challenging conditions of detention at immigration facility, alleging violations of due process and cruel and unusual punishment.',
  'U.S. District Court for the Western District of Texas',
  'Federal District',
  'El Paso',
  'Texas',
  '511 E San Antonio Ave, El Paso, TX 79901',
  '2025-11-25 10:30:00-07',
  'Class Certification Hearing',
  'Hon. Rachel Kim',
  'Rosa Martinez, et al.',
  'U.S. Immigration and Customs Enforcement',
  true,
  NULL,
  NULL,
  'Courtroom 5',
  ARRAY['ACLU Border Rights Center', 'Refugee and Immigrant Center for Education and Legal Services'],
  ARRAY['Due Process', 'Conditions of Confinement', 'Class Action'],
  NULL,
  'Hearing on motion for class certification',
  'scheduled'
),

(
  'Students for Fair Admissions v. University',
  '2023-CV-9821',
  'Education',
  'Challenge to race-conscious admissions policies under Equal Protection Clause and Title VI.',
  'U.S. Court of Appeals for the Fifth Circuit',
  'Federal Appeals',
  'New Orleans',
  'Louisiana',
  '600 S Maestri Pl, New Orleans, LA 70130',
  '2025-12-01 09:00:00-06',
  'Oral Arguments',
  'Panel of Three Judges',
  'Students for Fair Admissions',
  'University of Texas',
  true,
  'https://ca5.zoomgov.com/j/5551234567',
  '888-684-8852',
  'Ceremonial Courtroom',
  ARRAY['Students for Fair Admissions'],
  ARRAY['Equal Protection', 'Affirmative Action', 'Title VI'],
  NULL,
  'Appeals court oral arguments following district court decision',
  'scheduled'
),

(
  'Williams v. State Department of Corrections',
  '2024-CV-3342',
  'Civil Rights',
  'Conditions of confinement lawsuit alleging unconstitutional medical care in state prison system.',
  'U.S. District Court for the Middle District of Alabama',
  'Federal District',
  'Montgomery',
  'Alabama',
  '1 Church St, Montgomery, AL 36104',
  '2025-11-22 13:00:00-06',
  'Status Conference',
  'Hon. James Thompson',
  'DeShawn Williams',
  'Alabama Department of Corrections',
  true,
  'https://almd.zoomgov.com/j/7778889999',
  NULL,
  'Courtroom 1',
  ARRAY['Equal Justice Initiative', 'Southern Poverty Law Center'],
  ARRAY['Eighth Amendment', 'Deliberate Indifference', 'Medical Care'],
  NULL,
  'Status conference regarding discovery disputes',
  'scheduled'
),

(
  'Disability Rights Advocates v. Transit Authority',
  '2024-CV-6754',
  'Accessibility',
  'ADA Title II lawsuit alleging public transit system fails to provide accessible transportation for wheelchair users and violation of Rehabilitation Act.',
  'U.S. District Court for the Eastern District of New York',
  'Federal District',
  'Brooklyn',
  'New York',
  '225 Cadman Plaza E, Brooklyn, NY 11201',
  '2025-11-28 11:00:00-05',
  'Settlement Conference',
  'Magistrate Judge Sarah Brown',
  'Disability Rights Advocates of New York',
  'Metropolitan Transit Authority',
  true,
  NULL,
  NULL,
  'Conference Room 4B',
  ARRAY['Disability Rights Advocates', 'Disability Justice Network'],
  ARRAY['ADA Title II', 'Rehabilitation Act', 'Transportation Access'],
  NULL,
  'Court-ordered settlement conference',
  'scheduled'
),

(
  'Smith v. County Sheriff Department',
  '2024-CV-2211',
  'Police Misconduct',
  'Wrongful death action under Section 1983 alleging use of excessive deadly force. Family seeks damages for constitutional violations.',
  'U.S. District Court for the District of Minnesota',
  'Federal District',
  'Minneapolis',
  'Minnesota',
  '300 S 4th St, Minneapolis, MN 55415',
  '2025-12-05 09:30:00-06',
  'Trial',
  'Hon. Patricia Anderson',
  'Smith Family Estate',
  'Hennepin County Sheriff Department',
  true,
  NULL,
  '888-363-4749',
  'Courtroom 8W',
  ARRAY['National Lawyers Guild', 'Communities United Against Police Brutality'],
  ARRAY['Fourth Amendment', 'Excessive Force', 'Wrongful Death'],
  NULL,
  'First day of jury trial',
  'scheduled'
),

(
  'ACLU v. State Legislature',
  '2024-CV-5567',
  'First Amendment',
  'Challenge to anti-protest statute as unconstitutional restriction on freedom of speech and assembly.',
  'U.S. District Court for the Middle District of Florida',
  'Federal District',
  'Tampa',
  'Florida',
  '801 N Florida Ave, Tampa, FL 33602',
  '2025-11-30 10:00:00-05',
  'Preliminary Injunction Hearing',
  'Hon. Michael Stevens',
  'American Civil Liberties Union of Florida',
  'Florida Legislature',
  true,
  'https://flmd.zoomgov.com/j/3334445555',
  NULL,
  'Courtroom 3',
  ARRAY['ACLU of Florida', 'First Amendment Foundation'],
  ARRAY['First Amendment', 'Freedom of Speech', 'Freedom of Assembly'],
  'https://www.aclufl.org/',
  'Seeking to block enforcement of new protest restrictions',
  'scheduled'
),

(
  'Tenants Union v. Housing Authority',
  '2024-CV-7788',
  'Housing',
  'Fair Housing Act lawsuit alleging discriminatory eviction practices against families with children and people with disabilities.',
  'U.S. District Court for the Western District of Washington',
  'Federal District',
  'Seattle',
  'Washington',
  '700 Stewart St, Seattle, WA 98101',
  '2025-12-03 14:00:00-08',
  'Motion Hearing',
  'Hon. Lisa Wang',
  'Seattle Tenants Union',
  'King County Housing Authority',
  true,
  'https://wawd.zoomgov.com/j/6667778888',
  NULL,
  'Courtroom 14',
  ARRAY['Northwest Justice Project', 'Housing Justice Project'],
  ARRAY['Fair Housing Act', 'Familial Status', 'Disability Discrimination'],
  NULL,
  'Motion for preliminary injunction to halt evictions',
  'scheduled'
),

(
  'Anderson v. School District',
  '2024-CV-4455',
  'Education',
  'Title IX sexual harassment lawsuit by student alleging school district failed to respond to reports of assault and created hostile environment.',
  'U.S. District Court for the District of Colorado',
  'Federal District',
  'Denver',
  'Colorado',
  '901 19th St, Denver, CO 80294',
  '2025-11-26 09:00:00-07',
  'Motion to Dismiss Hearing',
  'Hon. Robert Garcia',
  'Jane Anderson (pseudonym)',
  'Denver Public Schools',
  true,
  'https://cod.zoomgov.com/j/1112223333',
  '888-684-8852',
  'Courtroom 7',
  ARRAY['National Women''s Law Center', 'Victim Rights Law Center'],
  ARRAY['Title IX', 'Sexual Harassment', 'Deliberate Indifference'],
  NULL,
  'School district motion to dismiss',
  'scheduled'
),

-- Completed recent cases (for reference)
(
  'Jones v. City Police Officers',
  '2023-CV-6621',
  'Police Misconduct',
  'Section 1983 excessive force case resulting in jury verdict for plaintiff. Awarded $2.5 million in damages.',
  'U.S. District Court for the Northern District of Illinois',
  'Federal District',
  'Chicago',
  'Illinois',
  '219 S Dearborn St, Chicago, IL 60604',
  '2025-10-15 09:00:00-05',
  'Jury Verdict',
  'Hon. Thomas Williams',
  'Tyrone Jones',
  'Chicago Police Officers Daniels and Smith',
  true,
  NULL,
  NULL,
  'Courtroom 2525',
  ARRAY['People''s Law Office', 'National Police Accountability Project'],
  ARRAY['Fourth Amendment', 'Excessive Force', 'Municipal Liability'],
  NULL,
  'Jury found officers violated Fourth Amendment rights',
  'completed'
),

(
  'Workers United v. Employer Corporation',
  '2023-CV-8833',
  'Employment',
  'Title VII class action alleging pattern and practice of race and sex discrimination in hiring and promotions. Case settled for $15 million.',
  'U.S. District Court for the Southern District of New York',
  'Federal District',
  'New York',
  'New York',
  '500 Pearl St, New York, NY 10007',
  '2025-10-28 14:00:00-04',
  'Settlement Approval Hearing',
  'Hon. Katherine Johnson',
  'Workers United Local 342',
  'National Retail Corporation',
  true,
  NULL,
  NULL,
  'Courtroom 26D',
  ARRAY['NAACP Legal Defense Fund', 'Equal Rights Advocates'],
  ARRAY['Title VII', 'Pattern and Practice', 'Class Action'],
  NULL,
  'Court approved $15M settlement with injunctive relief',
  'completed'
),

(
  'Indigenous Rights Coalition v. State Government',
  '2022-CV-9954',
  'Voting Rights',
  'Voting Rights Act case challenging lack of Native American language assistance and polling locations on reservations.',
  'U.S. District Court for the District of Arizona',
  'Federal District',
  'Phoenix',
  'Arizona',
  '401 W Washington St, Phoenix, AZ 85003',
  '2025-09-20 10:00:00-07',
  'Trial',
  'Hon. Maria Gonzales',
  'Indigenous Rights Coalition of Arizona',
  'Arizona Secretary of State',
  true,
  NULL,
  NULL,
  'Courtroom 4',
  ARRAY['Native American Rights Fund', 'Lawyers Committee for Civil Rights'],
  ARRAY['Voting Rights Act', 'Language Assistance', 'Equal Access'],
  NULL,
  'Consent decree requiring language assistance and additional polling sites',
  'completed'
);
