-- Generated from extract-state-data.js

-- Insert state laws data
INSERT INTO public.state_laws (state, state_code, recording_consent_type, recording_law_details, police_recording_details, can_record_police, has_shield_law, shield_law_details, assembly_rights_details, activist_protections) VALUES
(
  'Alabama',
  'AL',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Alabama rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Alabama protect peaceful protest and public gathering.',
  'Activists in Alabama can document police activity, organize protests, and access legal observer networks.'
),
(
  'Alaska',
  'AK',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Alaska rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Alaska protect peaceful protest and public gathering.',
  'Activists in Alaska can document police activity, organize protests, and access legal observer networks.'
),
(
  'Arizona',
  'AZ',
  'one-party',
  'One-party consent state. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Arizona rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Arizona protect peaceful protest and public gathering.',
  'Activists in Arizona can document police activity, organize protests, and access legal observer networks.'
),
(
  'Arkansas',
  'AR',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Arkansas rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Arkansas protect peaceful protest and public gathering.',
  'Activists in Arkansas can document police activity, organize protests, and access legal observer networks.'
),
(
  'California',
  'CA',
  'two-party',
  'All parties must consent to private recordings. Police recording in public is protected by First Amendment.',
  'Legal in public',
  true,
  false,
  'Journalists in California rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in California protect peaceful protest and public gathering.',
  'Activists in California can document police activity, organize protests, and access legal observer networks.'
),
(
  'Colorado',
  'CO',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Colorado rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Colorado protect peaceful protest and public gathering.',
  'Activists in Colorado can document police activity, organize protests, and access legal observer networks.'
),
(
  'Connecticut',
  'CT',
  'two-party',
  'All parties must consent. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Connecticut rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Connecticut protect peaceful protest and public gathering.',
  'Activists in Connecticut can document police activity, organize protests, and access legal observer networks.'
),
(
  'Delaware',
  'DE',
  'two-party',
  'All parties must consent to private recordings. Recording police in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Delaware rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Delaware protect peaceful protest and public gathering.',
  'Activists in Delaware can document police activity, organize protests, and access legal observer networks.'
),
(
  'Florida',
  'FL',
  'two-party',
  'All parties must consent to private recordings. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Florida rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Florida protect peaceful protest and public gathering.',
  'Activists in Florida can document police activity, organize protests, and access legal observer networks.'
),
(
  'Georgia',
  'GA',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Georgia rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Georgia protect peaceful protest and public gathering.',
  'Activists in Georgia can document police activity, organize protests, and access legal observer networks.'
),
(
  'Hawaii',
  'HI',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Hawaii rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Hawaii protect peaceful protest and public gathering.',
  'Activists in Hawaii can document police activity, organize protests, and access legal observer networks.'
),
(
  'Idaho',
  'ID',
  'one-party',
  'One-party consent state. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Idaho rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Idaho protect peaceful protest and public gathering.',
  'Activists in Idaho can document police activity, organize protests, and access legal observer networks.'
),
(
  'Illinois',
  'IL',
  'two-party',
  'Illinois requires all-party consent. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Illinois rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Illinois protect peaceful protest and public gathering.',
  'Activists in Illinois can document police activity, organize protests, and access legal observer networks.'
),
(
  'Indiana',
  'IN',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Indiana rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Indiana protect peaceful protest and public gathering.',
  'Activists in Indiana can document police activity, organize protests, and access legal observer networks.'
),
(
  'Iowa',
  'IA',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Iowa rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Iowa protect peaceful protest and public gathering.',
  'Activists in Iowa can document police activity, organize protests, and access legal observer networks.'
),
(
  'Kansas',
  'KS',
  'one-party',
  'One-party consent state. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Kansas rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Kansas protect peaceful protest and public gathering.',
  'Activists in Kansas can document police activity, organize protests, and access legal observer networks.'
),
(
  'Kentucky',
  'KY',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Kentucky rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Kentucky protect peaceful protest and public gathering.',
  'Activists in Kentucky can document police activity, organize protests, and access legal observer networks.'
),
(
  'Louisiana',
  'LA',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Louisiana rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Louisiana protect peaceful protest and public gathering.',
  'Activists in Louisiana can document police activity, organize protests, and access legal observer networks.'
),
(
  'Maine',
  'ME',
  'one-party',
  'One-party consent state. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Maine rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Maine protect peaceful protest and public gathering.',
  'Activists in Maine can document police activity, organize protests, and access legal observer networks.'
),
(
  'Maryland',
  'MD',
  'two-party',
  'All parties must consent. Recording police in public is constitutionally protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Maryland rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Maryland protect peaceful protest and public gathering.',
  'Activists in Maryland can document police activity, organize protests, and access legal observer networks.'
),
(
  'Massachusetts',
  'MA',
  'two-party',
  'All parties must consent to private recordings. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Massachusetts rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Massachusetts protect peaceful protest and public gathering.',
  'Activists in Massachusetts can document police activity, organize protests, and access legal observer networks.'
),
(
  'Michigan',
  'MI',
  'two-party',
  'All parties must consent. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Michigan rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Michigan protect peaceful protest and public gathering.',
  'Activists in Michigan can document police activity, organize protests, and access legal observer networks.'
),
(
  'Minnesota',
  'MN',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Minnesota rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Minnesota protect peaceful protest and public gathering.',
  'Activists in Minnesota can document police activity, organize protests, and access legal observer networks.'
),
(
  'Mississippi',
  'MS',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Mississippi rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Mississippi protect peaceful protest and public gathering.',
  'Activists in Mississippi can document police activity, organize protests, and access legal observer networks.'
),
(
  'Missouri',
  'MO',
  'one-party',
  'One-party consent state. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Missouri rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Missouri protect peaceful protest and public gathering.',
  'Activists in Missouri can document police activity, organize protests, and access legal observer networks.'
),
(
  'Montana',
  'MT',
  'two-party',
  'All parties must consent. Recording police in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Montana rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Montana protect peaceful protest and public gathering.',
  'Activists in Montana can document police activity, organize protests, and access legal observer networks.'
),
(
  'Nebraska',
  'NE',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Nebraska rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Nebraska protect peaceful protest and public gathering.',
  'Activists in Nebraska can document police activity, organize protests, and access legal observer networks.'
),
(
  'Nevada',
  'NV',
  'two-party',
  'All parties must consent to private recordings. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Nevada rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Nevada protect peaceful protest and public gathering.',
  'Activists in Nevada can document police activity, organize protests, and access legal observer networks.'
),
(
  'New Hampshire',
  'NH',
  'two-party',
  'All parties must consent. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in New Hampshire rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in New Hampshire protect peaceful protest and public gathering.',
  'Activists in New Hampshire can document police activity, organize protests, and access legal observer networks.'
),
(
  'New Jersey',
  'NJ',
  'one-party',
  'One-party consent state. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in New Jersey rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in New Jersey protect peaceful protest and public gathering.',
  'Activists in New Jersey can document police activity, organize protests, and access legal observer networks.'
),
(
  'New Mexico',
  'NM',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in New Mexico rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in New Mexico protect peaceful protest and public gathering.',
  'Activists in New Mexico can document police activity, organize protests, and access legal observer networks.'
),
(
  'New York',
  'NY',
  'one-party',
  'Only one party needs to consent to recordings. Recording police is constitutionally protected.',
  'Legal in public',
  true,
  false,
  'Journalists in New York rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in New York protect peaceful protest and public gathering.',
  'Activists in New York can document police activity, organize protests, and access legal observer networks.'
),
(
  'North Carolina',
  'NC',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in North Carolina rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in North Carolina protect peaceful protest and public gathering.',
  'Activists in North Carolina can document police activity, organize protests, and access legal observer networks.'
),
(
  'North Dakota',
  'ND',
  'one-party',
  'One-party consent state. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in North Dakota rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in North Dakota protect peaceful protest and public gathering.',
  'Activists in North Dakota can document police activity, organize protests, and access legal observer networks.'
),
(
  'Ohio',
  'OH',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Ohio rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Ohio protect peaceful protest and public gathering.',
  'Activists in Ohio can document police activity, organize protests, and access legal observer networks.'
),
(
  'Oklahoma',
  'OK',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Oklahoma rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Oklahoma protect peaceful protest and public gathering.',
  'Activists in Oklahoma can document police activity, organize protests, and access legal observer networks.'
),
(
  'Oregon',
  'OR',
  'two-party',
  'All parties must consent. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Oregon rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Oregon protect peaceful protest and public gathering.',
  'Activists in Oregon can document police activity, organize protests, and access legal observer networks.'
),
(
  'Pennsylvania',
  'PA',
  'two-party',
  'All parties must consent to private recordings. Recording police in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Pennsylvania rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Pennsylvania protect peaceful protest and public gathering.',
  'Activists in Pennsylvania can document police activity, organize protests, and access legal observer networks.'
),
(
  'Rhode Island',
  'RI',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Rhode Island rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Rhode Island protect peaceful protest and public gathering.',
  'Activists in Rhode Island can document police activity, organize protests, and access legal observer networks.'
),
(
  'South Carolina',
  'SC',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in South Carolina rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in South Carolina protect peaceful protest and public gathering.',
  'Activists in South Carolina can document police activity, organize protests, and access legal observer networks.'
),
(
  'South Dakota',
  'SD',
  'one-party',
  'One-party consent state. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in South Dakota rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in South Dakota protect peaceful protest and public gathering.',
  'Activists in South Dakota can document police activity, organize protests, and access legal observer networks.'
),
(
  'Tennessee',
  'TN',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Tennessee rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Tennessee protect peaceful protest and public gathering.',
  'Activists in Tennessee can document police activity, organize protests, and access legal observer networks.'
),
(
  'Texas',
  'TX',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Texas rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Texas protect peaceful protest and public gathering.',
  'Activists in Texas can document police activity, organize protests, and access legal observer networks.'
),
(
  'Utah',
  'UT',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Utah rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Utah protect peaceful protest and public gathering.',
  'Activists in Utah can document police activity, organize protests, and access legal observer networks.'
),
(
  'Vermont',
  'VT',
  'one-party',
  'One-party consent state. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in Vermont rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Vermont protect peaceful protest and public gathering.',
  'Activists in Vermont can document police activity, organize protests, and access legal observer networks.'
),
(
  'Virginia',
  'VA',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Virginia rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Virginia protect peaceful protest and public gathering.',
  'Activists in Virginia can document police activity, organize protests, and access legal observer networks.'
),
(
  'Washington',
  'WA',
  'two-party',
  'All parties must consent. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Washington rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Washington protect peaceful protest and public gathering.',
  'Activists in Washington can document police activity, organize protests, and access legal observer networks.'
),
(
  'West Virginia',
  'WV',
  'one-party',
  'One-party consent state. Public recordings of police are protected.',
  'Legal in public',
  true,
  false,
  'Journalists in West Virginia rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in West Virginia protect peaceful protest and public gathering.',
  'Activists in West Virginia can document police activity, organize protests, and access legal observer networks.'
),
(
  'Wisconsin',
  'WI',
  'one-party',
  'One-party consent state. Citizens may record police in public spaces.',
  'Legal in public',
  true,
  false,
  'Journalists in Wisconsin rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Wisconsin protect peaceful protest and public gathering.',
  'Activists in Wisconsin can document police activity, organize protests, and access legal observer networks.'
),
(
  'Wyoming',
  'WY',
  'one-party',
  'One-party consent state. Recording police officers in public is legal.',
  'Legal in public',
  true,
  false,
  'Journalists in Wyoming rely on state press freedom protections plus shield or reporter-privilege statutes.',
  'Constitutional assembly rights in Wyoming protect peaceful protest and public gathering.',
  'Activists in Wyoming can document police activity, organize protests, and access legal observer networks.'
)
;

-- Insert attorney data (national organizations)
INSERT INTO public.attorneys (name, firm, state, practice_areas, specialties, phone, email, website, bio) VALUES
(
  'Reporters Committee Legal Defense Network',
  'Reporters Committee for Freedom of the Press',
  'National',
  ARRAY['Press Freedom', 'FOIA', 'First Amendment'],
  NULL,
  NULL,
  NULL,
  'https://www.rcfp.org/legal-defense-network/',
  'Press shield defense, FOIA litigation, and subpoena responses.'
),
(
  'National Lawyers Guild Civil Rights Defense Team',
  'National Lawyers Guild',
  'National',
  ARRAY['Protest Rights', 'Police Accountability', 'Civil Rights'],
  NULL,
  NULL,
  NULL,
  'https://nationallawyersguild.org/our-programs/',
  'Protest defense, oversight of police, and activist legal training.'
),
(
  'Lawyers'' Committee for Civil Rights Under Law',
  'Lawyers'' Committee for Civil Rights Under Law',
  'National',
  ARRAY['Voting Rights', 'Police Accountability', 'Civil Rights'],
  NULL,
  NULL,
  NULL,
  'https://lawyerscommittee.org/',
  'Citizen review boards, voting rights, and anti-retaliation litigation.'
),
(
  'Civil Rights Corps Legal Advocates',
  'Civil Rights Corps',
  'National',
  ARRAY['Police Misconduct', 'Protest Rights', 'Class Action'],
  NULL,
  NULL,
  NULL,
  'https://civilrightscorps.org/',
  'Class-action support for excessive policing and protest retaliation.'
),
(
  'Alabama Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Alabama',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Alabama facing retaliation or unlawful arrests.'
),
(
  'Alaska Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Alaska',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Alaska facing retaliation or unlawful arrests.'
),
(
  'Arizona Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Arizona',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Arizona facing retaliation or unlawful arrests.'
),
(
  'Arkansas Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Arkansas',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Arkansas facing retaliation or unlawful arrests.'
),
(
  'California Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'California',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in California facing retaliation or unlawful arrests.'
),
(
  'Colorado Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Colorado',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Colorado facing retaliation or unlawful arrests.'
),
(
  'Connecticut Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Connecticut',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Connecticut facing retaliation or unlawful arrests.'
),
(
  'Delaware Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Delaware',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Delaware facing retaliation or unlawful arrests.'
),
(
  'Florida Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Florida',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Florida facing retaliation or unlawful arrests.'
),
(
  'Georgia Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Georgia',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Georgia facing retaliation or unlawful arrests.'
),
(
  'Hawaii Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Hawaii',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Hawaii facing retaliation or unlawful arrests.'
),
(
  'Idaho Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Idaho',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Idaho facing retaliation or unlawful arrests.'
),
(
  'Illinois Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Illinois',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Illinois facing retaliation or unlawful arrests.'
),
(
  'Indiana Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Indiana',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Indiana facing retaliation or unlawful arrests.'
),
(
  'Iowa Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Iowa',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Iowa facing retaliation or unlawful arrests.'
),
(
  'Kansas Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Kansas',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Kansas facing retaliation or unlawful arrests.'
),
(
  'Kentucky Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Kentucky',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Kentucky facing retaliation or unlawful arrests.'
),
(
  'Louisiana Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Louisiana',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Louisiana facing retaliation or unlawful arrests.'
),
(
  'Maine Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Maine',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Maine facing retaliation or unlawful arrests.'
),
(
  'Maryland Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Maryland',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Maryland facing retaliation or unlawful arrests.'
),
(
  'Massachusetts Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Massachusetts',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Massachusetts facing retaliation or unlawful arrests.'
),
(
  'Michigan Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Michigan',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Michigan facing retaliation or unlawful arrests.'
),
(
  'Minnesota Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Minnesota',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Minnesota facing retaliation or unlawful arrests.'
),
(
  'Mississippi Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Mississippi',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Mississippi facing retaliation or unlawful arrests.'
),
(
  'Missouri Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Missouri',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Missouri facing retaliation or unlawful arrests.'
),
(
  'Montana Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Montana',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Montana facing retaliation or unlawful arrests.'
),
(
  'Nebraska Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Nebraska',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Nebraska facing retaliation or unlawful arrests.'
),
(
  'Nevada Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Nevada',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Nevada facing retaliation or unlawful arrests.'
),
(
  'New Hampshire Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'New Hampshire',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in New Hampshire facing retaliation or unlawful arrests.'
),
(
  'New Jersey Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'New Jersey',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in New Jersey facing retaliation or unlawful arrests.'
),
(
  'New Mexico Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'New Mexico',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in New Mexico facing retaliation or unlawful arrests.'
),
(
  'New York Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'New York',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in New York facing retaliation or unlawful arrests.'
),
(
  'North Carolina Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'North Carolina',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in North Carolina facing retaliation or unlawful arrests.'
),
(
  'North Dakota Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'North Dakota',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in North Dakota facing retaliation or unlawful arrests.'
),
(
  'Ohio Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Ohio',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Ohio facing retaliation or unlawful arrests.'
),
(
  'Oklahoma Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Oklahoma',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Oklahoma facing retaliation or unlawful arrests.'
),
(
  'Oregon Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Oregon',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Oregon facing retaliation or unlawful arrests.'
),
(
  'Pennsylvania Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Pennsylvania',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Pennsylvania facing retaliation or unlawful arrests.'
),
(
  'Rhode Island Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Rhode Island',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Rhode Island facing retaliation or unlawful arrests.'
),
(
  'South Carolina Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'South Carolina',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in South Carolina facing retaliation or unlawful arrests.'
),
(
  'South Dakota Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'South Dakota',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in South Dakota facing retaliation or unlawful arrests.'
),
(
  'Tennessee Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Tennessee',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Tennessee facing retaliation or unlawful arrests.'
),
(
  'Texas Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Texas',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Texas facing retaliation or unlawful arrests.'
),
(
  'Utah Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Utah',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Utah facing retaliation or unlawful arrests.'
),
(
  'Vermont Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Vermont',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Vermont facing retaliation or unlawful arrests.'
),
(
  'Virginia Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Virginia',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Virginia facing retaliation or unlawful arrests.'
),
(
  'Washington Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Washington',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Washington facing retaliation or unlawful arrests.'
),
(
  'West Virginia Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'West Virginia',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in West Virginia facing retaliation or unlawful arrests.'
),
(
  'Wisconsin Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Wisconsin',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Wisconsin facing retaliation or unlawful arrests.'
),
(
  'Wyoming Civil Liberties Response Team',
  'ACLU Civil Rights Litigation',
  'Wyoming',
  ARRAY['Civil Rights', 'First Amendment', 'Police Accountability'],
  ARRAY['Protest Defense', 'Journalist Protection'],
  NULL,
  NULL,
  'https://www.aclu.org/legal',
  'Supporting activists, journalists, and whistleblowers in Wyoming facing retaliation or unlawful arrests.'
),
(
  'Alabama Justice Advocates',
  'Southern Justice Collective',
  'Alabama',
  ARRAY['Civil Rights', 'Criminal Defense', 'Police Accountability'],
  ARRAY['Protest Defense', 'Legal Observer Coordination'],
  '205-555-0148',
  'helpline@sojustal.org',
  'https://sojustal.org',
  'Rapid response legal team covering Birmingham, Montgomery, and Huntsville protests.'
),
(
  'Alaska Arctic Civil Rights Defense',
  'Northern Justice Project',
  'Alaska',
  ARRAY['Civil Rights', 'Constitutional Law', 'Indigenous Rights'],
  ARRAY['Police Accountability', 'Mutual Aid Support'],
  '907-555-0199',
  'support@arcticrights.org',
  'https://arcticrights.org',
  'Anchorage-based attorneys coordinating statewide protest defense and legal observer trainings.'
),
(
  'Arizona Protest Legal Alliance',
  'Desert Justice Law Center',
  'Arizona',
  ARRAY['Civil Rights', 'Immigration', 'Police Accountability'],
  ARRAY['Mass Defense', 'Bail Support'],
  '602-555-0182',
  'intake@desertjustice.org',
  'https://desertjustice.org',
  'Phoenix and Tucson coverage for protest arrests, immigrant rights defense, and rapid response hotlines.'
),
(
  'Arkansas Movement Defense',
  'Ozark Civil Rights Law Group',
  'Arkansas',
  ARRAY['Civil Rights', 'Criminal Defense', 'Labor Rights'],
  ARRAY['Protest Defense', 'Record Expungement'],
  '501-555-0170',
  'action@ozarkrights.org',
  'https://ozarkrights.org',
  'Little Rock-based network supporting grassroots organizers and community journalists.'
),
(
  'California Movement Lawyering Hub',
  'Golden State Rights Center',
  'California',
  ARRAY['Civil Rights', 'Police Accountability', 'Public Records'],
  ARRAY['Mass Defense', 'Digital Rights'],
  '415-555-0126',
  'intake@goldenstaterights.org',
  'https://goldenstaterights.org',
  'Statewide coordination for protest defense, SB 1421 records, and legal observer deployment.'
),
(
  'Colorado Freedom Defense Network',
  'Front Range Civil Rights Attorneys',
  'Colorado',
  ARRAY['Civil Rights', 'Police Accountability', 'Civil Litigation'],
  ARRAY['Mass Defense', 'Policy Advocacy'],
  '303-555-0164',
  'support@frcrattorneys.org',
  'https://frcrattorneys.org',
  'Denver-led rapid response covering Front Range demonstrations and court support.'
),
(
  'Connecticut First Amendment Counsel',
  'Constitution State Rights Lawyers',
  'Connecticut',
  ARRAY['Civil Rights', 'Media Law', 'Police Accountability'],
  ARRAY['Press Freedom', 'Protest Defense'],
  '203-555-0194',
  'press@csr-law.org',
  'https://csr-law.org',
  'Hartford and New Haven attorneys focused on journalist protection and protest defense.'
),
(
  'Delaware Protest Support Collective',
  'First State Justice Center',
  'Delaware',
  ARRAY['Civil Rights', 'Criminal Defense', 'Youth Advocacy'],
  ARRAY['Protest Defense', 'Know Your Rights Training'],
  '302-555-0168',
  'support@firststatejustice.org',
  'https://firststatejustice.org',
  'Statewide hotline providing counsel for protest arrests and activist legal education.'
),
(
  'Florida Justice Rapid Response',
  'Sunshine State Legal Collective',
  'Florida',
  ARRAY['Civil Rights', 'Police Accountability', 'Immigration'],
  ARRAY['Mass Defense', 'Legal Observer Coordination'],
  '786-555-0142',
  'rapidresponse@sslc.org',
  'https://sslc.org',
  'Miami-based team coordinating statewide representation for protest-related cases and ICE holds.'
),
(
  'Georgia People''s Defense Project',
  'Peach State Justice Center',
  'Georgia',
  ARRAY['Civil Rights', 'Police Accountability', 'Voting Rights'],
  ARRAY['Protest Defense', 'Community Legal Clinics'],
  '404-555-0135',
  'help@psjustice.org',
  'https://psjustice.org',
  'Atlanta attorneys organizing mass defense, election protection, and protest support hotlines.'
),
(
  'Hawaii Civil Liberties Barristers',
  'Pacific Rights Law Group',
  'Hawaii',
  ARRAY['Civil Rights', 'Environmental Justice', 'Police Accountability'],
  ARRAY['Protest Defense', 'Indigenous Rights Support'],
  '808-555-0177',
  'aloha@pacificrightslaw.org',
  'https://pacificrightslaw.org',
  'Honolulu collective protecting Mauna Kea, land defense, and civil liberties demonstrators.'
),
(
  'Idaho People''s Law Collective',
  'Gem State Rights Defense',
  'Idaho',
  ARRAY['Civil Rights', 'Criminal Defense', 'Environmental Justice'],
  ARRAY['Protest Defense', 'Mutual Aid Support'],
  '208-555-0180',
  'intake@gemstaterights.org',
  'https://gemstaterights.org',
  'Boise-based attorneys covering rural and urban demonstrations with remote intake options.'
),
(
  'Illinois Movement Legal Aid',
  'Lakefront Civil Rights Firm',
  'Illinois',
  ARRAY['Civil Rights', 'Police Accountability', 'Labor Rights'],
  ARRAY['Mass Defense', 'Strategic Litigation'],
  '312-555-0112',
  'support@lakefrontcivilrights.org',
  'https://lakefrontcivilrights.org',
  'Chicago-centered legal team handling CPD misconduct, protest arrests, and union picket defense.'
),
(
  'Indiana Protest Legal Team',
  'Crossroads Justice Collective',
  'Indiana',
  ARRAY['Civil Rights', 'Criminal Defense', 'Education Law'],
  ARRAY['Protest Defense', 'Student Advocacy'],
  '317-555-0156',
  'helpline@crossroadsjustice.org',
  'https://crossroadsjustice.org',
  'Indianapolis attorneys defending student activists and coordinating statewide jail support.'
),
(
  'Iowa Rights Defense Network',
  'Heartland Justice Partners',
  'Iowa',
  ARRAY['Civil Rights', 'Agricultural Labor', 'Police Accountability'],
  ARRAY['Protest Defense', 'Policy Advocacy'],
  '515-555-0175',
  'support@heartlandjustice.org',
  'https://heartlandjustice.org',
  'Des Moines-led attorneys serving protestors across the state with bilingual intake lines.'
),
(
  'Kansas Justice Support Attorneys',
  'Prairie Civil Liberties Group',
  'Kansas',
  ARRAY['Civil Rights', 'Criminal Defense', 'Press Freedom'],
  ARRAY['Protest Defense', 'FOIA Appeals'],
  '785-555-0161',
  'intake@prairieclg.org',
  'https://prairieclg.org',
  'Wichita and Lawrence coverage focusing on journalist protections and protest-related arrests.'
),
(
  'Kentucky Freedom Counsel',
  'Bluegrass Rights Center',
  'Kentucky',
  ARRAY['Civil Rights', 'Police Accountability', 'Prisoners'' Rights'],
  ARRAY['Protest Defense', 'Legislative Advocacy'],
  '502-555-0186',
  'support@bluegrassrights.org',
  'https://bluegrassrights.org',
  'Louisville-based attorneys offering 24/7 hotline coverage for protest arrests and jail support.'
),
(
  'Louisiana Protest Legal Collaborative',
  'Bayou Justice Advocates',
  'Louisiana',
  ARRAY['Civil Rights', 'Police Accountability', 'Environmental Justice'],
  ARRAY['Protest Defense', 'Community Education'],
  '504-555-0144',
  'rapidresponse@bayoujustice.org',
  'https://bayoujustice.org',
  'New Orleans lawyers covering Gulf South environmental justice demonstrations and protest arrests.'
),
(
  'Maine Movement Legal Alliance',
  'Pine Tree Rights Center',
  'Maine',
  ARRAY['Civil Rights', 'Environmental Justice', 'Police Accountability'],
  ARRAY['Protest Defense', 'Mutual Aid Support'],
  '207-555-0121',
  'help@pinetreerights.org',
  'https://pinetreerights.org',
  'Portland attorneys assisting land defenders, indigenous organizers, and protest arrestees.'
),
(
  'Maryland Civil Rights Rapid Response',
  'Chesapeake Justice Partners',
  'Maryland',
  ARRAY['Civil Rights', 'Police Accountability', 'Housing Justice'],
  ARRAY['Protest Defense', 'Record Expungement'],
  '410-555-0190',
  'support@chesapeakejustice.org',
  'https://chesapeakejustice.org',
  'Baltimore-centered lawyers providing protest defense, impact litigation, and expungement clinics.'
),
(
  'Massachusetts Protest Legal Collective',
  'Bay State Justice Network',
  'Massachusetts',
  ARRAY['Civil Rights', 'Labor Rights', 'Police Accountability'],
  ARRAY['Mass Defense', 'Campus Organizing Support'],
  '617-555-0139',
  'intake@baystatejustice.org',
  'https://baystatejustice.org',
  'Boston legal collective coordinating statewide representation and digital rights support.'
),
(
  'Michigan People''s Justice Center',
  'Great Lakes Civil Rights Firm',
  'Michigan',
  ARRAY['Civil Rights', 'Police Accountability', 'Environmental Justice'],
  ARRAY['Protest Defense', 'Civil Litigation'],
  '313-555-0109',
  'help@greatlakesrights.org',
  'https://greatlakesrights.org',
  'Detroit-based attorneys covering Flint water justice organizing and statewide protests.'
),
(
  'Minnesota Freedom Defense Lawyers',
  'Twin Cities Justice Cooperative',
  'Minnesota',
  ARRAY['Civil Rights', 'Police Accountability', 'Civil Litigation'],
  ARRAY['Mass Defense', 'Policy Reform'],
  '612-555-0118',
  'support@tcjusticecoop.org',
  'https://tcjusticecoop.org',
  'Minneapolis-St. Paul network leading mass defense coordination and civil litigation follow-up.'
),
(
  'Mississippi Justice Hotline',
  'Magnolia State Rights Center',
  'Mississippi',
  ARRAY['Civil Rights', 'Police Accountability', 'Voting Rights'],
  ARRAY['Protest Defense', 'Community Clinics'],
  '601-555-0153',
  'hotline@magnoliarights.org',
  'https://magnoliarights.org',
  'Jackson attorneys staffing 24-hour hotline for protest arrests and voter intimidation claims.'
),
(
  'Missouri Movement Law Project',
  'Gateway Civil Rights Group',
  'Missouri',
  ARRAY['Civil Rights', 'Police Accountability', 'Housing Justice'],
  ARRAY['Protest Defense', 'Strategic Litigation'],
  '314-555-0128',
  'support@gatewayrights.org',
  'https://gatewayrights.org',
  'St. Louis and Kansas City attorneys representing protestors and pursuing consent decrees.'
),
(
  'Montana Civil Rights Defense Unit',
  'Big Sky Justice Collective',
  'Montana',
  ARRAY['Civil Rights', 'Environmental Justice', 'Indigenous Rights'],
  ARRAY['Protest Defense', 'Policy Advocacy'],
  '406-555-0184',
  'intake@bigskyjustice.org',
  'https://bigskyjustice.org',
  'Bozeman-led lawyers defending land defenders, water protectors, and protest arrestees.'
),
(
  'Nebraska Justice Solidarity Network',
  'Heartland Rights Advocates',
  'Nebraska',
  ARRAY['Civil Rights', 'Police Accountability', 'Immigration'],
  ARRAY['Protest Defense', 'Detention Support'],
  '402-555-0166',
  'support@heartlandrights.org',
  'https://heartlandrights.org',
  'Omaha and Lincoln attorneys covering immigrant justice rallies and community defense.'
),
(
  'Nevada Protest Defense Alliance',
  'Silver State Justice Center',
  'Nevada',
  ARRAY['Civil Rights', 'Police Accountability', 'Entertainment Law'],
  ARRAY['Protest Defense', 'Legal Observer Coordination'],
  '702-555-0133',
  'intake@silverstaterights.org',
  'https://silverstaterights.org',
  'Las Vegas legal collective handling Strip demonstrations and bail coordination.'
),
(
  'New Hampshire Freedom Counsel',
  'Granite State Rights Lawyers',
  'New Hampshire',
  ARRAY['Civil Rights', 'Police Accountability', 'First Amendment'],
  ARRAY['Protest Defense', 'Press Freedom'],
  '603-555-0146',
  'support@graniterights.org',
  'https://graniterights.org',
  'Manchester-based attorneys aiding protestors, citizen journalists, and local organizers.'
),
(
  'New Jersey Protest Support Lawyers',
  'Garden State Justice Collaborative',
  'New Jersey',
  ARRAY['Civil Rights', 'Police Accountability', 'Housing Justice'],
  ARRAY['Mass Defense', 'Policy Advocacy'],
  '201-555-0192',
  'help@gardenstatejustice.org',
  'https://gardenstatejustice.org',
  'Newark and Camden attorneys coordinating mass defense teams and civil litigation follow-up.'
),
(
  'New Mexico Civil Rights Barristers',
  'Rio Grande Justice Center',
  'New Mexico',
  ARRAY['Civil Rights', 'Police Accountability', 'Environmental Justice'],
  ARRAY['Protest Defense', 'Indigenous Rights Support'],
  '505-555-0115',
  'intake@riograndejustice.org',
  'https://riograndejustice.org',
  'Albuquerque-Santa Fe coverage for land defense, water protection, and protest arrests.'
),
(
  'New York Movement Counsel',
  'Liberty City Law Collective',
  'New York',
  ARRAY['Civil Rights', 'Police Accountability', 'Public Records'],
  ARRAY['Mass Defense', 'Press Freedom'],
  '646-555-0101',
  'intake@libertycitylaw.org',
  'https://libertycitylaw.org',
  'New York City-based attorneys coordinating borough-specific defense and FOIL litigation.'
),
(
  'North Carolina Justice Action Team',
  'Piedmont Civil Liberties Project',
  'North Carolina',
  ARRAY['Civil Rights', 'Police Accountability', 'Education Law'],
  ARRAY['Protest Defense', 'Campus Organizing Support'],
  '919-555-0188',
  'support@piedmontclp.org',
  'https://piedmontclp.org',
  'Raleigh-Durham attorneys supporting HBCU organizers and statewide protest response.'
),
(
  'North Dakota Civil Liberties Defense',
  'Red River Justice Network',
  'North Dakota',
  ARRAY['Civil Rights', 'Environmental Justice', 'Indigenous Rights'],
  ARRAY['Protest Defense', 'Mutual Aid Support'],
  '701-555-0179',
  'helpline@redriverjustice.org',
  'https://redriverjustice.org',
  'Fargo and Bismarck lawyers assisting pipeline resistance and rural protestors.'
),
(
  'Ohio Protest Legal Alliance',
  'Buckeye Justice Advocates',
  'Ohio',
  ARRAY['Civil Rights', 'Police Accountability', 'Labor Rights'],
  ARRAY['Mass Defense', 'Record Expungement'],
  '614-555-0131',
  'support@buckeyejustice.org',
  'https://buckeyejustice.org',
  'Columbus-based attorneys coordinating with Cleveland and Cincinnati legal support teams.'
),
(
  'Oklahoma Justice Defense Network',
  'Red Dirt Rights Center',
  'Oklahoma',
  ARRAY['Civil Rights', 'Police Accountability', 'Environmental Justice'],
  ARRAY['Protest Defense', 'Tribal Advocacy'],
  '405-555-0123',
  'intake@reddirtrights.org',
  'https://reddirtrights.org',
  'Oklahoma City and Tulsa attorneys defending environmental and indigenous protestors.'
),
(
  'Oregon Movement Justice Lawyers',
  'Cascade Civil Rights Collective',
  'Oregon',
  ARRAY['Civil Rights', 'Police Accountability', 'Environmental Justice'],
  ARRAY['Mass Defense', 'Policy Reform'],
  '503-555-0107',
  'support@cascadejustice.org',
  'https://cascadejustice.org',
  'Portland-based team managing protest defense, legal observers, and policy advocacy.'
),
(
  'Pennsylvania Protest Legal Aid',
  'Keystone Justice Network',
  'Pennsylvania',
  ARRAY['Civil Rights', 'Police Accountability', 'Voting Rights'],
  ARRAY['Mass Defense', 'Record Expungement'],
  '215-555-0185',
  'help@keystonejustice.org',
  'https://keystonejustice.org',
  'Philadelphia-Pittsburgh coverage for protest arrests, voter suppression, and jail support.'
),
(
  'Rhode Island Movement Defense',
  'Ocean State Rights Center',
  'Rhode Island',
  ARRAY['Civil Rights', 'Police Accountability', 'Housing Justice'],
  ARRAY['Protest Defense', 'Community Education'],
  '401-555-0159',
  'support@oceanstaterights.org',
  'https://oceanstaterights.org',
  'Providence-based attorneys offering small state coverage and multilingual intake.'
),
(
  'South Carolina Justice Watch',
  'Palmetto Civil Rights Advocates',
  'South Carolina',
  ARRAY['Civil Rights', 'Police Accountability', 'Labor Rights'],
  ARRAY['Protest Defense', 'Community Legal Clinics'],
  '803-555-0172',
  'intake@palmettorights.org',
  'https://palmettorights.org',
  'Columbia and Charleston attorneys providing protest defense and workplace justice support.'
),
(
  'South Dakota Rights Defense Collective',
  'Prairie Freedom Lawyers',
  'South Dakota',
  ARRAY['Civil Rights', 'Environmental Justice', 'Indigenous Rights'],
  ARRAY['Protest Defense', 'Mutual Aid Support'],
  '605-555-0147',
  'support@prairiefreedom.org',
  'https://prairiefreedom.org',
  'Rapid City and Sioux Falls attorneys backing pipeline resistance and protest defense.'
),
(
  'Tennessee People''s Defense',
  'Volunteer State Justice Network',
  'Tennessee',
  ARRAY['Civil Rights', 'Police Accountability', 'Education Law'],
  ARRAY['Protest Defense', 'Campus Organizing Support'],
  '615-555-0163',
  'help@volunteerjustice.org',
  'https://volunteerjustice.org',
  'Nashville-based attorneys offering statewide protest defense and campus free speech support.'
),
(
  'Texas Movement Law Alliance',
  'Lone Star Rights Center',
  'Texas',
  ARRAY['Civil Rights', 'Police Accountability', 'Immigration'],
  ARRAY['Mass Defense', 'Bail Support'],
  '512-555-0124',
  'intake@lonestarrights.org',
  'https://lonestarrights.org',
  'Austin-Houston-Dallas coordination for protest defense, immigration enforcement, and bail funds.'
),
(
  'Utah Civil Liberties Defense',
  'Wasatch Justice Collective',
  'Utah',
  ARRAY['Civil Rights', 'Religious Freedom', 'Police Accountability'],
  ARRAY['Protest Defense', 'Policy Advocacy'],
  '385-555-0178',
  'support@wasatchjustice.org',
  'https://wasatchjustice.org',
  'Salt Lake City attorneys defending protestors and advocating for legislative reforms.'
),
(
  'Vermont Freedom Defense Team',
  'Green Mountain Rights Center',
  'Vermont',
  ARRAY['Civil Rights', 'Environmental Justice', 'Police Accountability'],
  ARRAY['Protest Defense', 'Mutual Aid Support'],
  '802-555-0129',
  'help@greenmountainrights.org',
  'https://greenmountainrights.org',
  'Burlington and Brattleboro lawyers covering rural protests and civil liberties trainings.'
),
(
  'Virginia Protest Legal Support',
  'Commonwealth Justice Partners',
  'Virginia',
  ARRAY['Civil Rights', 'Police Accountability', 'Voting Rights'],
  ARRAY['Mass Defense', 'Policy Advocacy'],
  '804-555-0160',
  'support@commonwealthjustice.org',
  'https://commonwealthjustice.org',
  'Richmond-based attorneys coordinating statewide protest defense and legislative advocacy.'
),
(
  'Washington Movement Defense Lawyers',
  'Cascade Freedom Attorneys',
  'Washington',
  ARRAY['Civil Rights', 'Police Accountability', 'Environmental Justice'],
  ARRAY['Mass Defense', 'Press Freedom'],
  '206-555-0114',
  'intake@cascadefreedom.org',
  'https://cascadefreedom.org',
  'Seattle-Tacoma-Spokane coverage for protest defense, public records, and journalist support.'
),
(
  'West Virginia Civil Rights Helpline',
  'Mountain State Justice Collective',
  'West Virginia',
  ARRAY['Civil Rights', 'Labor Rights', 'Police Accountability'],
  ARRAY['Protest Defense', 'Community Education'],
  '304-555-0187',
  'help@mountainstatejustice.org',
  'https://mountainstatejustice.org',
  'Charleston attorneys running a statewide helpline for protest defense and workplace retaliation.'
),
(
  'Wisconsin Justice Rapid Response',
  'Badger State Rights Center',
  'Wisconsin',
  ARRAY['Civil Rights', 'Police Accountability', 'Environmental Justice'],
  ARRAY['Mass Defense', 'Record Expungement'],
  '414-555-0158',
  'support@badgerstaterights.org',
  'https://badgerstaterights.org',
  'Milwaukee and Madison attorneys providing protest defense, court support, and expungement clinics.'
),
(
  'Wyoming Freedom Legal Collaborative',
  'High Plains Justice Network',
  'Wyoming',
  ARRAY['Civil Rights', 'Environmental Justice', 'Indigenous Rights'],
  ARRAY['Protest Defense', 'Mutual Aid Support'],
  '307-555-0174',
  'support@highplainsjustice.org',
  'https://highplainsjustice.org',
  'Cheyenne and Laramie attorneys assisting land defenders, indigenous organizers, and protest arrestees.'
);

