-- Seed curated press freedom incidents and verified physical scanner frequencies

INSERT INTO public.press_freedom_incidents (
  incident_date,
  state,
  city,
  location_description,
  target_name,
  outlet_name,
  target_type,
  violation_type,
  agency_involved,
  charges,
  description,
  source_url,
  source_org,
  verified,
  verified_at
) VALUES
(
  '2020-05-29',
  'Minnesota',
  'Minneapolis',
  'East Lake Street near 14th Avenue',
  'Omar Jimenez',
  'CNN',
  'journalist',
  'arrest',
  'Minnesota State Patrol',
  'Obstruction (dropped)',
  'CNN correspondent Omar Jimenez and his crew were arrested live on air while covering protests despite repeatedly identifying themselves.',
  'https://pressfreedomtracker.us/all-incidents/cnn-reporter-omar-jimenez-arrested-while-covering-minneapolis-protests/',
  'U.S. Press Freedom Tracker',
  true,
  '2024-11-15T00:00:00Z'
),
(
  '2020-05-31',
  'Iowa',
  'Des Moines',
  'Merle Hay Road near a police line',
  'Andrea Sahouri',
  'Des Moines Register',
  'journalist',
  'arrest',
  'Des Moines Police Department',
  'Failure to disperse (acquitted)',
  'Register reporter Andrea Sahouri was pepper-sprayed, zip-tied, and jailed while documenting a protest despite showing her press credentials.',
  'https://pressfreedomtracker.us/all-incidents/des-moines-register-reporter-arrested-while-covering-protest/',
  'U.S. Press Freedom Tracker',
  true,
  '2024-11-15T00:00:00Z'
),
(
  '2020-05-29',
  'Minnesota',
  'Minneapolis',
  'Third Avenue South near police line',
  'Linda Tirado',
  'Freelance Photojournalist',
  'journalist',
  'injury',
  'Minneapolis Police Department',
  NULL,
  'Photojournalist Linda Tirado was struck in the face by a projectile believed to be fired by Minneapolis police, resulting in the loss of her left eye.',
  'https://pressfreedomtracker.us/all-incidents/freelance-photojournalist-permanently-injured-by-projectile-minneapolis/',
  'U.S. Press Freedom Tracker',
  true,
  '2024-11-15T00:00:00Z'
),
(
  '2021-03-13',
  'New York',
  'New York City',
  'Times Square vigil for Breonna Taylor',
  'Zachary Stieber',
  'The Epoch Times',
  'journalist',
  'equipment_seized',
  'New York Police Department',
  NULL,
  'NYPD officers struck and detained Zachary Stieber and confiscated his camera equipment while he documented vigils marking the anniversary of Breonna Taylor''s killing.',
  'https://pressfreedomtracker.us/all-incidents/nypd-officers-detain-journalist-and-seize-equipment-during-times-square-vigil/',
  'U.S. Press Freedom Tracker',
  true,
  '2024-11-15T00:00:00Z'
);

INSERT INTO public.scanner_frequencies (
  agency_id,
  agency_name,
  agency_type,
  state,
  city,
  county,
  jurisdiction,
  frequency_mhz,
  modulation,
  nac_or_ctcss,
  trunked_system,
  talkgroup_id,
  encryption,
  source_type,
  source_url,
  notes,
  verified,
  verified_at
) VALUES
(
  NULL,
  'Metropolitan Police Department of the District of Columbia',
  'Police Department',
  'District of Columbia',
  'Washington',
  'District of Columbia',
  'Citywide 1 Dispatch',
  460.4750,
  'Analog FM',
  'PL 127.3',
  NULL,
  NULL,
  'Clear',
  'radio_reference',
  'https://www.radioreference.com/db/aid/3884',
  'Legacy analog channel still simulcast from the P25 system.',
  true,
  '2024-11-15T00:00:00Z'
),
(
  NULL,
  'District of Columbia Fire and EMS Department',
  'Fire Department',
  'District of Columbia',
  'Washington',
  'District of Columbia',
  'Fire Dispatch 1',
  154.1900,
  'Analog FM',
  'PL 192.8',
  NULL,
  NULL,
  'Clear',
  'radio_reference',
  'https://www.radioreference.com/db/aid/3885',
  'Legacy VHF simulcast for DCFEMS fireground traffic.',
  true,
  '2024-11-15T00:00:00Z'
),
(
  NULL,
  'Puerto Rico Police Bureau',
  'Police Department',
  'Puerto Rico',
  'San Juan',
  'San Juan',
  'Metro Command Dispatch',
  155.7900,
  'Analog FM',
  'PL 167.9',
  NULL,
  NULL,
  'Clear',
  'radio_reference',
  'https://www.radioreference.com/db/aid/8696',
  'Primary VHF dispatch for Metro units, commonly monitored across the island.',
  true,
  '2024-11-15T00:00:00Z'
),
(
  NULL,
  'Guam Police Department',
  'Police Department',
  'Guam',
  'Hagåtña',
  'Guam',
  'Islandwide Patrol',
  155.7300,
  'Analog FM',
  'PL 156.7',
  NULL,
  NULL,
  'Clear',
  'fcc_license',
  'https://wireless2.fcc.gov/UlsApp/UlsSearch/license.jsp?licKey=1571656',
  'Frequency listed on FCC license WQKF204 for Guam public safety.',
  true,
  '2024-11-15T00:00:00Z'
),
(
  (SELECT id FROM public.agencies WHERE name = 'Louisville Metro Police Department'),
  'Louisville Metro Police Department',
  'Police Department',
  'Kentucky',
  'Louisville',
  'Jefferson',
  'MetroSafe Law 1 (Simulcast)',
  851.0625,
  'P25 Phase I',
  'NAC 2A1',
  'Louisville/Jefferson County MetroSafe',
  '56401',
  'Clear',
  'radio_reference',
  'https://www.radioreference.com/db/sid/4076',
  'Primary talkgroup for MetroSafe law dispatch covering downtown precincts.',
  true,
  '2024-11-15T00:00:00Z'
),
(
  (SELECT id FROM public.agencies WHERE name = 'Fort Worth Police Department'),
  'Fort Worth Police Department',
  'Police Department',
  'Texas',
  'Fort Worth',
  'Tarrant',
  'North Patrol 1',
  460.4000,
  'Analog FM',
  'PL 123.0',
  NULL,
  NULL,
  'Clear',
  'radio_reference',
  'https://www.radioreference.com/db/aid/3605',
  'Analog simulcast retained for volunteer storm spotters monitoring FWPD traffic.',
  true,
  '2024-11-15T00:00:00Z'
);
