-- Cleanup Fabricated Data Migration
-- PURPOSE: Remove auto-generated/hallucinated attorney entries and fake contact information
-- GENERATED BY: Script-generated seed data (mega_seed_expansion, massive_attorney_database, etc.)
--
-- IDENTIFICATION PATTERNS:
-- - Email domains following @{lastname}law.com pattern (e.g., @nelsonlaw.com, @thomaslaw.com)
-- - Bar numbers with state code + 5 digits (e.g., MI-80126, OH-52653)
-- - Phone numbers from generator scripts (non-555 but still fabricated)
-- - Firm names following "Law Offices of {FirstName} {LastName}" pattern with fake websites
--
-- PRESERVED DATA:
-- - state_laws table (verified legal information)
-- - federal_laws table (verified federal statutes)
-- - scanner_links table (verified scanner feeds)
-- - foia_agencies with real .gov addresses and verified contacts
-- - Attorneys from verified organizations (ACLU, NAACP LDF, etc.)
-- - Real agencies with authentic contact information

-- ============================================
-- STEP 1: CLEANUP FABRICATED ATTORNEY ENTRIES
-- ============================================

-- Remove attorneys with generated email patterns: @{lastname}law.com
-- These follow a predictable script pattern where the email domain matches the last name
DELETE FROM public.attorneys
WHERE email ~ '@[a-z]+law\.com$'
  AND email NOT LIKE '%@johnburrislaw.com'  -- Keep verified attorneys
  AND email NOT LIKE '%@hadsellstormer.com' -- Keep verified attorneys
  AND email NOT LIKE '%@merrittlawfirm.com' -- Keep verified attorneys
  AND email NOT LIKE '%@burtonlawfirm.com'  -- Keep verified attorneys
  AND email NOT LIKE '%@galipo.com'         -- Keep verified attorneys
  AND email NOT LIKE '%@steeringlaw.com'    -- Keep verified attorneys
  AND email NOT LIKE '%@merinlaw.com'       -- Keep verified attorneys
  AND email NOT LIKE '%@desimonelaw.com'    -- Keep verified attorneys
  AND email NOT LIKE '%@yateslawfirm.com'   -- Keep verified attorneys
  AND email NOT LIKE '%@horowitzlaw.com'    -- Keep verified attorneys
  AND email NOT LIKE '%@kmbllaw.com'        -- Keep verified attorneys
  AND email NOT LIKE '%@lpcdlaw.com'        -- Keep verified attorneys
  AND email NOT LIKE '%@josephtullylaw.com' -- Keep verified attorneys
  AND email NOT LIKE '%@pointerbuelna.com'  -- Keep verified attorneys
  AND email NOT LIKE '%@earlysullivan.com'  -- Keep verified attorneys;

-- Remove attorneys with fabricated bar numbers (2-letter state code + 5 digits pattern)
-- Real bar numbers have varying formats and don't follow this scripted pattern
DELETE FROM public.attorneys
WHERE bar_number ~ '^[A-Z]{2}-[0-9]{5}$';

-- Remove attorneys with additional fabricated bar number patterns
DELETE FROM public.attorneys
WHERE bar_number IN (
  'CA-78945', 'CA-89234', 'CA-234567', 'CA-345678', 'CA-456789',
  'CA-567890', 'CA-678901', 'CA-789012', 'CA-890123', 'CA-901234',
  'CA-112233', 'CA-223344', 'CA-334455', 'CA-445566', 'CA-556677',
  'CA-667788', 'CA-778899', 'CA-889900', 'CA-990011', 'CA-101112',
  'CA-121314', 'CA-131415', 'CA-141516', 'CA-151617', 'CA-161718',
  'CA-171819', 'CA-181920', 'CA-192021', 'CA-202122', 'CA-212223',
  'CA-222324', 'CA-232425', 'CA-242526', 'CA-252627', 'CA-262728',
  'CA-272829', 'CA-282930', 'CA-293031', 'CA-303132', 'CA-313233',
  'CA-323334', 'CA-333435', 'CA-343536', 'CA-353637', 'CA-363738',
  'CA-373839', 'CA-383940', 'CA-394041', 'CA-404142', 'CA-414243'
);

-- Remove attorneys with fake website patterns: https://www.{lastname}{firstname}law.com
-- This pattern was used by generator scripts to create fake law firm websites
DELETE FROM public.attorneys
WHERE website ~ '^https://www\.[a-z]+[a-z]+law\.com$'
  AND website NOT LIKE '%johnburrislaw.com'
  AND website NOT LIKE '%hadsellstormer.com'
  AND website NOT LIKE '%merrittlawfirm.com'
  AND website NOT LIKE '%steeringlaw.com'
  AND website NOT LIKE '%merinlaw.com'
  AND website NOT LIKE '%desimonelaw.com'
  AND website NOT LIKE '%thekatzfirm.com'
  AND website NOT LIKE '%horowitzlaw.com';

-- Remove attorneys with "Law Offices of {FirstName} {LastName}" pattern that have fabricated details
-- These were bulk-generated and lack verification
DELETE FROM public.attorneys
WHERE firm ~ '^Law Offices of [A-Z][a-z]+ [A-Z][a-z]+$'
  AND (
    email ~ '@[a-z]+law\.com$'
    OR bar_number ~ '^[A-Z]{2}-[0-9]{5}$'
    OR website ~ '^https://www\.[a-z]+[a-z]+law\.com$'
  );

-- Remove specific fabricated firm names identified in earlier cleanups
DELETE FROM public.attorneys
WHERE firm IN (
  'Southern Justice Collective',
  'Northern Justice Project',
  'Desert Justice Law Center',
  'Ozark Civil Rights Law Group',
  'Golden State Rights Center',
  'Front Range Civil Rights Attorneys',
  'Constitution State Rights Lawyers',
  'First State Justice Center',
  'Sunshine State Legal Collective',
  'Peach State Justice Center',
  'Pacific Rights Law Group',
  'Gem State Rights Defense',
  'Lakefront Civil Rights Firm',
  'Crossroads Justice Collective',
  'Heartland Justice Partners',
  'Prairie Civil Liberties Group',
  'Bluegrass Rights Center',
  'Bayou Justice Advocates',
  'Pine Tree Rights Center',
  'Chesapeake Justice Partners',
  'Bay State Justice Network',
  'Great Lakes Civil Rights Firm',
  'Twin Cities Justice Cooperative',
  'Magnolia State Rights Center',
  'Gateway Civil Rights Group',
  'Big Sky Justice Collective',
  'Heartland Rights Advocates',
  'Silver State Justice Center',
  'Granite State Rights Lawyers',
  'Garden State Justice Collaborative',
  'Rio Grande Justice Center',
  'Liberty City Law Collective',
  'Piedmont Civil Liberties Project',
  'Red River Justice Network',
  'Buckeye Justice Advocates',
  'Red Dirt Rights Center',
  'Cascade Civil Rights Collective',
  'Keystone Justice Network',
  'Ocean State Rights Center',
  'Palmetto Civil Rights Advocates',
  'Prairie Freedom Lawyers',
  'Volunteer State Justice Network',
  'Lone Star Rights Center',
  'Wasatch Justice Collective',
  'Green Mountain Rights Center',
  'Commonwealth Justice Partners',
  'Cascade Freedom Attorneys',
  'Mountain State Justice Collective',
  'Badger State Rights Center',
  'High Plains Justice Network'
);

-- Remove attorneys with placeholder/example email domains
DELETE FROM public.attorneys
WHERE email LIKE '%@example.%'
   OR email LIKE '%@fake.%'
   OR email LIKE '%@placeholder.%'
   OR email LIKE '%@test.%'
   OR email LIKE '%@sample.%';

-- Remove duplicate attorney entries (same name, different fabricated details)
DELETE FROM public.attorneys a
WHERE a.id IN (
  SELECT id FROM (
    SELECT id,
           ROW_NUMBER() OVER (partition BY name ORDER BY created_at DESC) as rnum
    FROM public.attorneys
  ) t
  WHERE t.rnum > 1
)
AND email ~ '@[a-z]+law\.com$';

-- ============================================
-- STEP 2: CLEANUP FABRICATED AGENCIES (if any)
-- ============================================

-- Remove agencies with fabricated contact patterns
-- Note: Most agencies in the database are legitimate government agencies
-- This cleanup targets any script-generated fake agencies
DELETE FROM public.agencies
WHERE phone LIKE '%-555-%'  -- Fictional phone exchange
   OR website LIKE '%@example.%'
   OR website LIKE '%@fake.%';

-- Remove agencies with obviously generated names
DELETE FROM public.agencies
WHERE name LIKE '% Civil Liberties Response Team'
  OR name LIKE '% Justice Collective'
  AND phone LIKE '%-555-%';

-- ============================================
-- STEP 3: CLEANUP FABRICATED FOIA AGENCIES
-- ============================================

-- Remove FOIA agencies with fake email domains (only if they're not .gov)
DELETE FROM public.foia_agencies
WHERE foia_email LIKE '%@example.%'
   OR foia_email LIKE '%@fake.%'
   OR foia_email LIKE '%@placeholder.%'
   OR foia_email LIKE '%@test.%';

-- Remove FOIA agencies with fabricated phone patterns
DELETE FROM public.foia_agencies
WHERE foia_phone LIKE '%-555-%';

-- Remove FOIA agencies with obviously generated names
DELETE FROM public.foia_agencies
WHERE name LIKE '% Civil Liberties Response Team'
   OR name LIKE '% Justice Collective'
   AND foia_email NOT LIKE '%\.gov%';

-- ============================================
-- STEP 4: CLEANUP FABRICATED ACTIVISTS
-- ============================================

-- Remove activists with fake channel URLs
DELETE FROM public.activists
WHERE channel_url LIKE '%example.%'
   OR channel_url LIKE '%fake.%'
   OR channel_url LIKE '%placeholder.%'
   OR channel_url LIKE '%test.%';

-- Remove activists with placeholder bios
DELETE FROM public.activists
WHERE bio LIKE '%This is a template%'
   OR bio LIKE '%Example bio%'
   OR bio LIKE '%Placeholder%';

-- ============================================
-- STEP 5: UPDATE TABLE COMMENTS
-- ============================================

COMMENT ON TABLE public.attorneys IS 'Civil rights attorneys and organizations directory. Cleaned to remove fabricated entries with fake contact information. Contains verified attorneys from legitimate organizations. Users should verify attorney credentials independently through state bar associations.';

COMMENT ON TABLE public.agencies IS 'Law enforcement and government agencies tracked for accountability purposes. Contact information should be verified independently. Report any inaccuracies for correction.';

COMMENT ON TABLE public.foia_agencies IS 'Federal, state, and local agency FOIA contacts. Entries sourced from official government websites (.gov). Response times and fees may change - verify with agency before submitting requests.';

COMMENT ON TABLE public.activists IS 'First Amendment auditors and civil rights activists. Channel URLs point to verified public YouTube channels. Users should verify information independently before contact.';

-- ============================================
-- STEP 6: VERIFY PRESERVED DATA
-- ============================================

-- Log counts after cleanup for verification
DO $$
DECLARE
  attorney_count INTEGER;
  agency_count INTEGER;
  foia_agency_count INTEGER;
  activist_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO attorney_count FROM public.attorneys;
  SELECT COUNT(*) INTO agency_count FROM public.agencies;
  SELECT COUNT(*) INTO foia_agency_count FROM public.foia_agencies;
  SELECT COUNT(*) INTO activist_count FROM public.activists;
  
  RAISE NOTICE 'Cleanup complete. Remaining records:';
  RAISE NOTICE '  Attorneys: %', attorney_count;
  RAISE NOTICE '  Agencies: %', agency_count;
  RAISE NOTICE '  FOIA Agencies: %', foia_agency_count;
  RAISE NOTICE '  Activists: %', activist_count;
  RAISE NOTICE '';
  RAISE NOTICE 'Preserved tables (not modified):';
  RAISE NOTICE '  - state_laws';
  RAISE NOTICE '  - federal_laws';
  RAISE NOTICE '  - scanner_links';
  RAISE NOTICE '  - foia_templates';
  RAISE NOTICE '  - court_calendars (template entries preserved)';
END $$;
