// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("⚠️  Supabase environment variables not configured");
  console.warn("The app will continue with limited functionality.");
  console.warn("Configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to enable database features.");
} else {
  console.log("✅ Supabase client initialized");
  console.log("   URL:", SUPABASE_URL);
}

const createDummyClient = (): SupabaseClient<Database> => {
  const unresolved = { data: null, error: new Error("Supabase not configured") } as const;
  const promise = Promise.resolve(unresolved);

  const createDummyQueryBuilder = () => {
    const builder: Record<string, unknown> = {};
    Object.assign(builder, {
      select: () => builder,
      insert: () => builder,
      update: () => builder,
      delete: () => builder,
      eq: () => builder,
      or: () => builder,
      order: () => builder,
      limit: () => builder,
      in: () => builder,
      single: () => promise,
      maybeSingle: () => promise,
      then: promise.then.bind(promise),
      catch: promise.catch.bind(promise),
      finally: promise.finally.bind(promise),
    });
    return builder;
  };

  const dummyChannel = {
    on: () => dummyChannel,
    subscribe: () => dummyChannel,
    unsubscribe: () => {},
  } as unknown as ReturnType<SupabaseClient<Database>["channel"]>;

  return {
    from: () => createDummyQueryBuilder(),
    auth: {
      signUp: () => promise,
      signInWithPassword: () => promise,
      signOut: () => promise,
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } }, error: null }),
    },
    storage: {
      from: () => ({
        upload: () => promise,
        download: () => promise,
        getPublicUrl: () => ({ data: { publicUrl: "" }, error: new Error("Supabase not configured") }),
      }),
    },
    channel: () => dummyChannel,
    removeChannel: () => {},
  } as unknown as SupabaseClient<Database>;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient<Database> = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createDummyClient();
