// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Browser-safe configuration validation. Production deployment performs a stricter
// secret/configuration gate before publishing; local docs/static builds remain usable.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("Supabase environment variables are not configured; account and database features are disabled.");
} else {
  try {
    const parsed = new URL(SUPABASE_URL);
    if (parsed.protocol !== "https:") throw new Error("Supabase URL must use HTTPS");
  } catch {
    throw new Error("VITE_SUPABASE_URL must be a valid HTTPS URL");
  }
}

const createDummyClient = (): SupabaseClient<Database> => {
  const unresolved = { data: null, error: new Error("Supabase not configured") } as const;
  const promise = Promise.resolve(unresolved);

  const createDummyQueryBuilder = () => {
    const builder: Record<string, unknown> = {};
    Object.assign(builder, {
      select: () => builder,
      insert: () => builder,
      update: () => builder,
      delete: () => builder,
      upsert: () => builder,
      eq: () => builder,
      neq: () => builder,
      gt: () => builder,
      gte: () => builder,
      lt: () => builder,
      lte: () => builder,
      or: () => builder,
      order: () => builder,
      limit: () => builder,
      range: () => builder,
      in: () => builder,
      single: () => promise,
      maybeSingle: () => promise,
      then: promise.then.bind(promise),
      catch: promise.catch.bind(promise),
      finally: promise.finally.bind(promise),
    });
    return builder;
  };

  const dummyChannel = {
    on: () => dummyChannel,
    subscribe: () => dummyChannel,
    unsubscribe: () => {},
  } as unknown as ReturnType<SupabaseClient<Database>["channel"]>;

  return {
    from: () => createDummyQueryBuilder(),
    rpc: () => promise,
    auth: {
      signUp: () => promise,
      signInWithPassword: () => promise,
      signOut: () => promise,
      resetPasswordForEmail: () => promise,
      updateUser: () => promise,
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } }, error: null }),
    },
    storage: {
      from: () => ({
        upload: () => promise,
        download: () => promise,
        remove: () => promise,
        createSignedUrl: () => promise,
        getPublicUrl: () => ({ data: { publicUrl: "" }, error: new Error("Supabase not configured") }),
      }),
    },
    channel: () => dummyChannel,
    removeChannel: () => {},
  } as unknown as SupabaseClient<Database>;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase: SupabaseClient<Database> = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    })
  : createDummyClient();
